model:  
  _target_: multiobjective.models.cnn.CNNModel

  num_classes: 10

genome_cfg:
  size: 8

  slices:
    conv_layers: [0, 1]
    neurons_conv: [1, 4]
    dropout: [4, 6]
    neurons_dense: [6, 8]

  mappings:
    conv_layers_genes:
      "0": 2
      "1": 3

    neurons_conv_genes:
      "000": 32
      "001": 64
      "010": 96
      "011": 128
      "100": 192
      "101": 256
      "110": 384
      "111": 512

    dropout_genes:
      "00": 0.0
      "01": 0.10
      "10": 0.25
      "11": 0.40

    neurons_dense_genes:
      "00": 32
      "01": 64
      "10": 128
      "11": 256
